package com.solution.smartTution.model;
// Generated Apr 17, 2019 11:31:41 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lesson generated by hbm2java
 */
@Entity
@Table(name="lesson"
    ,catalog="tution"
)
public class Lesson  implements java.io.Serializable {


     private int id;
     private TutionClass tutionClass;
     private Byte completed;
     private String name;
     private int classIdclass;
     private int classTeacherId1;
     private Set<Tute> tutes = new HashSet<Tute>(0);

    public Lesson() {
    }

	
    public Lesson(int id, TutionClass tutionClass, int classIdclass, int classTeacherId1) {
        this.id = id;
        this.tutionClass = tutionClass;
        this.classIdclass = classIdclass;
        this.classTeacherId1 = classTeacherId1;
    }
    public Lesson(int id, TutionClass tutionClass, Byte completed, String name, int classIdclass, int classTeacherId1, Set<Tute> tutes) {
       this.id = id;
       this.tutionClass = tutionClass;
       this.completed = completed;
       this.name = name;
       this.classIdclass = classIdclass;
       this.classTeacherId1 = classTeacherId1;
       this.tutes = tutes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tution_class_idclass", nullable=false)
    public TutionClass getTutionClass() {
        return this.tutionClass;
    }
    
    public void setTutionClass(TutionClass tutionClass) {
        this.tutionClass = tutionClass;
    }

    
    @Column(name="completed")
    public Byte getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(Byte completed) {
        this.completed = completed;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="class_idclass", nullable=false)
    public int getClassIdclass() {
        return this.classIdclass;
    }
    
    public void setClassIdclass(int classIdclass) {
        this.classIdclass = classIdclass;
    }

    
    @Column(name="class_teacher_id1", nullable=false)
    public int getClassTeacherId1() {
        return this.classTeacherId1;
    }
    
    public void setClassTeacherId1(int classTeacherId1) {
        this.classTeacherId1 = classTeacherId1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lesson")
    public Set<Tute> getTutes() {
        return this.tutes;
    }
    
    public void setTutes(Set<Tute> tutes) {
        this.tutes = tutes;
    }




}


