package com.solution.smartTution.model;
// Generated Apr 17, 2019 11:31:41 AM by Hibernate Tools 3.6.0


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher"
    ,catalog="tution"
)
public class Teacher  implements java.io.Serializable {


     private int id;
     private String name;
     private String qualification;
     private String experience;
     private String description;
     private Set<TutionClass> tutionClasses = new HashSet<TutionClass>(0);

    public Teacher() {
    }

	
    public Teacher(int id) {
        this.id = id;
    }
    public Teacher(int id, String name, String qualification, String experience, String description, Set<TutionClass> tutionClasses) {
       this.id = id;
       this.name = name;
       this.qualification = qualification;
       this.experience = experience;
       this.description = description;
       this.tutionClasses = tutionClasses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="qualification", length=45)
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    
    @Column(name="experience", length=45)
    public String getExperience() {
        return this.experience;
    }
    
    public void setExperience(String experience) {
        this.experience = experience;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teacher")
@JsonIgnore
    public Set<TutionClass> getTutionClasses() {
        return this.tutionClasses;
    }
    
    public void setTutionClasses(Set<TutionClass> tutionClasses) {
        this.tutionClasses = tutionClasses;
    }




}


