package com.solution.smartTution.model;
// Generated Apr 17, 2019 11:31:41 AM by Hibernate Tools 3.6.0


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tute generated by hbm2java
 */
@Entity
@Table(name="tute"
    ,catalog="tution"
)
public class Tute  implements java.io.Serializable {


     private int id;
     private Lesson lesson;
     private String name;
     private int lessonId;
     private int lessonClassIdclass;
     private int lessonClassTeacherId1;
     private byte[] picture;
     private Set<User> users = new HashSet<User>(0);

    public Tute() {
    }

	
    public Tute(int id, Lesson lesson, int lessonId, int lessonClassIdclass, int lessonClassTeacherId1) {
        this.id = id;
        this.lesson = lesson;
        this.lessonId = lessonId;
        this.lessonClassIdclass = lessonClassIdclass;
        this.lessonClassTeacherId1 = lessonClassTeacherId1;
    }
    public Tute(int id, Lesson lesson, String name, int lessonId, int lessonClassIdclass, int lessonClassTeacherId1, byte[] picture, Set<User> users) {
       this.id = id;
       this.lesson = lesson;
       this.name = name;
       this.lessonId = lessonId;
       this.lessonClassIdclass = lessonClassIdclass;
       this.lessonClassTeacherId1 = lessonClassTeacherId1;
       this.picture = picture;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lesson_id1", nullable=false)
    public Lesson getLesson() {
        return this.lesson;
    }
    
    public void setLesson(Lesson lesson) {
        this.lesson = lesson;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="lesson_id", nullable=false)
    public int getLessonId() {
        return this.lessonId;
    }
    
    public void setLessonId(int lessonId) {
        this.lessonId = lessonId;
    }

    
    @Column(name="lesson_class_idclass", nullable=false)
    public int getLessonClassIdclass() {
        return this.lessonClassIdclass;
    }
    
    public void setLessonClassIdclass(int lessonClassIdclass) {
        this.lessonClassIdclass = lessonClassIdclass;
    }

    
    @Column(name="lesson_class_teacher_id1", nullable=false)
    public int getLessonClassTeacherId1() {
        return this.lessonClassTeacherId1;
    }
    
    public void setLessonClassTeacherId1(int lessonClassTeacherId1) {
        this.lessonClassTeacherId1 = lessonClassTeacherId1;
    }

    
    @Column(name="picture")
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="tute_has_user", catalog="tution", joinColumns = { 
        @JoinColumn(name="tute_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="user_id", nullable=false, updatable=false) })

    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


